/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: fe8619bfcaec6d994c13fc2d3befcbfb)
interface __BaseEnv_Env {
	MEMORY_INDEX: VectorizeIndex;
	BROWSER: BrowserRun;
	AI: Ai;
	ASSETS: Fetcher;
	OPENAI_MODEL: "gpt-5.4-mini";
	OPENAI_EMBEDDING_MODEL: "text-embedding-3-small";
	JOOBLE_API_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_REDIRECT_URI: string;
	OPENAI_API_KEY: string;
	LLM_PROVIDER: string;
	OAUTH_TOKEN_ENCRYPTION_KEY?: string;
	LINKEDIN_BROWSER_SEARCH_URL?: string;
	LINKEDIN_BROWSER_API_TOKEN?: string;
	LINKEDIN_BROWSER_SESSION_ID?: string;
	CLOUDFLARE_ACCOUNT_ID?: string;
	BROWSER_RUN_API_TOKEN?: string;
	ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	SCHEDULE_MEETING_WORKFLOW: Workflow<Parameters<import("./src/server").ScheduleMeetingWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_MODEL" | "OPENAI_EMBEDDING_MODEL" | "JOOBLE_API_KEY" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "GOOGLE_REDIRECT_URI" | "OPENAI_API_KEY" | "LLM_PROVIDER">> {}
}
