/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 33efd3b17229f92f32173efc2e9ad735)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		AI: Ai;
		ASSETS: Fetcher;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
		JOOBLE_API_KEY?: string;
		GOOGLE_CLIENT_ID?: string;
		GOOGLE_CLIENT_SECRET?: string;
		GOOGLE_REDIRECT_URI?: string;
	}
}
interface Env extends Cloudflare.Env {}
